### ISSUE TITLE
Setup return value fails in a constellation with nullable ints

### ISSUE THREAD

**Issue by Kiechlus** [devlooped/moq#1223] opened 2021-12-07 14:17 UTC
Using moq version `4.16.1`

Setting a return value does not work when an optional nullable `int?` is setup as `It.IsAny<int>()`. However, the compiler does not complain neither. Finding out what was the problem took us quite some time, so this can be a real annoyance.
 
```c#
public class MockedClass
{
    public virtual string MockedMethod(int? pageIndex = null) => "test";
}

public class ClassToTest
{
    private readonly MockedClass mockedProperty = null;

    public ClassToTest(MockedClass mockedProperty)
    {
        this.mockedProperty = mockedProperty;
    }

    public string SomeMethod()
    {
        return mockedProperty.MockedMethod();
    }
}

[Fact]
public void Test()
{
    // Works as expected
    var mock = new Mock<MockedClass>();
    mock.Setup(x => x.MockedMethod(It.IsAny<int?>())).Returns("foobar");
    var classToTest = new ClassToTest(mock.Object);
    Assert.Equal("foobar", classToTest.SomeMethod()); // This works

    // Does not work
    var mock2 = new Mock<MockedClass>();
    mock2.Setup(x => x.MockedMethod(It.IsAny<int>())).Returns("foobar"); // Setting up as It.IsAny<int>
    var classToTest2 = new ClassToTest(mock2.Object);
    Assert.Equal("foobar", classToTest2.SomeMethod()); // This throws with null != "foobar"
}
```

A similar issue was reported on https://github.com/moq/moq4/issues/444 but could not be reproduced.

**Comment by stakx** [comment] 2022-05-12 17:02
This is a bug, and one that will not be trivial to fix. It involves the type checking logic in `Match<T>` which has been a culprit for more than one nullable value type issue in the past.

Note to self for future reference:

`Match<T>` has a [`CanCast` helper method which is supposed to protect the `Condition` predicate](https://github.com/moq/moq4/blob/6e98431e3bfea43cc21af96afd79dcd9b7ec051b/src/Moq/Match.cs#L183) from invalid (type-mismatched) input.

Unfortunately, in this case, things go wrong. We have a `Match<int>` but an argument `(int?)null`, and `CanCast` correctly deduces that `null` cannot be passed to `Condition` because it's not an `int`.

The type mismatch probably can't be resolved inside `Match<T>`. Ideally, we'd have created a `Match<int?>` in the first place not a `Match<int>`. This would involve Moq checking whether the matcher expression is then cast to a nullable type (i.e. check for the presence of a `Convert` expression node, i.e. `(T?)It.IsAny<T>()`. Unfortunately, as it stands, the cast gets lost while executing the matcher expression to identify it as such.

**Comment by stakx** [comment] 2022-05-13 14:36
Actually, I take that back, this is a (admittedly subtle) user mistake, not a bug in Moq: You've set up `MockedMethod` to return `"foobar"` when it gets called with any `int` value... but the method gets called with `null`, which is _not_ a valid `int` value; therefore the call to `MockedMethod` quite correctly doesn't match your setup. And since you haven't set `mock2.CallBase = true`, the base implementation (which would return `"test"`) gets ignored, too.

**Closed as completed** 2022-05-13 14:37 UTC
Labels: by design
