### ISSUE TITLE
The type initializer for 'Moq.Async.AwaitableFactory' threw an exception:  Could not load file or assembly 'System.Threading.Tasks.Extensions, Version=4.2.0.1

### ISSUE THREAD

**Issue by dariusz-wozniak** [devlooped/moq#1179] opened 2021-06-30 11:22 UTC
Hi,

Recently, I started having errors when running tests on the Azure DevOps. The error I'm receiving is written below. Please note that me and none of my colleagues don't receive these errors locally.

Error:

> System.IO.FileLoadException : Could not load file or assembly 'System.Threading.Tasks.Extensions, Version=4.2.0.1, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)

Stack:

> 2021-06-30T06:56:05.5745936Z --FileLoadException
> 2021-06-30T06:56:05.5746420Z    at Moq.Async.AwaitableFactory..cctor()
> 2021-06-30T06:56:05.5746913Z   Failed ShouldLeaveOnlySingleLineItemCommand [2 ms]
> 2021-06-30T06:56:05.5747373Z   Error Message:
> 2021-06-30T06:56:05.5748539Z    System.TypeInitializationException : The type initializer for 'Moq.Async.AwaitableFactory' threw an exception.
> 2021-06-30T06:56:05.5749806Z   ----> System.IO.FileLoadException : Could not load file or assembly 'System.Threading.Tasks.Extensions, Version=4.2.0.1, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)
> 2021-06-30T06:56:05.5750965Z   Stack Trace:
> 2021-06-30T06:56:05.5777963Z      at Moq.Async.AwaitableFactory.TryGet(Type type)
> 2021-06-30T06:56:05.5779246Z    at Moq.ExpressionExtensions.<Split>g__IsResult|5_1(MemberInfo member, IAwaitableFactory& awaitableFactory) in C:\projects\moq4\src\Moq\ExpressionExtensions.cs:line 345
> 2021-06-30T06:56:05.5783024Z    at Moq.ExpressionExtensions.<Split>g__Split|5_0(Expression e, Expression& r, InvocationShape& p, Boolean assignment, Boolean allowNonOverridableLastProperty) in C:\projects\moq4\src\Moq\ExpressionExtensions.cs:line 299
> 2021-06-30T06:56:05.5784569Z    at Moq.ExpressionExtensions.Split(LambdaExpression expression, Boolean allowNonOverridableLastProperty) in C:\projects\moq4\src\Moq\ExpressionExtensions.cs:line 149
> 2021-06-30T06:56:05.5785728Z    at Moq.Mock.SetupRecursive[TSetup](Mock mock, LambdaExpression expression, Func`4 setupLast, Boolean allowNonOverridableLastProperty) in C:\projects\moq4\src\Moq\Mock.cs:line 601
> 2021-06-30T06:56:05.5787008Z    at Moq.Mock.Setup(Mock mock, LambdaExpression expression, Condition condition) in C:\projects\moq4\src\Moq\Mock.cs:line 505
> 2021-06-30T06:56:05.5787879Z    at Moq.Mock`1.Setup[TResult](Expression`1 expression) in C:\projects\moq4\src\Moq\Mock`1.cs:line 454

A few tech details:

- Project target: NET Framework 4.7.2
- Moq: 4.16.1
- Azure Devops Task - Visual Studio Test: 2.170.1
- Microsoft Test Execution Command Line Tool: 16.10.0
- NUnit: 3.13.2
- NUnit Adapter: 4.0.0.0

`packages.config` entry:

```
<package id="System.Threading.Tasks.Extensions" version="4.5.4" targetFramework="net472" />
```

Binding redirect in `app.config`:

```
<dependentAssembly>
	<assemblyIdentity name="System.Threading.Tasks.Extensions" publicKeyToken="cc7b13ffcd2ddd51" culture="neutral" />
	<bindingRedirect oldVersion="0.0.0.0-4.2.0.1" newVersion="4.2.0.1" />
</dependentAssembly>
```

`.csproj` entry:

```
<Reference Include="System.Threading.Tasks.Extensions, Version=4.2.0.1, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51, processorArchitecture=MSIL">
  <HintPath>..\packages\System.Threading.Tasks.Extensions.4.5.4\lib\net461\System.Threading.Tasks.Extensions.dll</HintPath>
</Reference>
```

I had several trials, but none of these helped solving the issue.

I've found Moq 4.16.x for .NET Framework 4.5 uses reference to the System.Threading.Tasks.Extensions 4.2.0.1, not 4.5.4. Could it be an issue in my case?

![image](https://user-images.githubusercontent.com/5969160/123952254-09f85400-d9a6-11eb-9ec5-32e3bdf140ad.png)

Thanks

**Comment by stakx** [comment] 2021-06-30 12:19
There have been many similar issues re: assembly versioning / binding redirects, they usually turn out to be a project configuration problem unrelated to Moq. I suggest you do a search for some possible solutions. I'm going to close this as off-topic; other than staying up-to-date with NuGet dependencies, there's not much we can do.

**Closed as completed by stakx** 2021-06-30 12:19 UTC

**Comment by dariusz-wozniak** [comment] 2021-06-30 13:08
@stakx: I reviewed GitHub issues and StackOverflow threads for the Moq and other projects, but haven't found working solution.

One thing that is exceptional in case of that exception is that error is happening on the Azure DevOps context, not the local environment one.

**Comment by dariusz-wozniak** [comment] 2021-06-30 14:18
As per above, can you please re-open the issue, @stakx?

**Comment by stakx** [comment] 2021-06-30 14:56
No, this is more of an issue with NuGet's ridiculous versioning problems, it's not an issue caused by Moq. The only thing we _can_ do is updating the versions of Moq's dependencies (such as the one on System.Threading.Tasks.Extensions), but even if we don't, you should still be able to resolve the issue by configuring your project differently. (For example, depending on the targeted frameworks, you can often force a specific version of a NuGet package by referencing it in your main project. There's also a few different ways to configure binding redirects for the .NET Framework.) But this isn't the right place to help you do that &ndash; this is the issue tracker for Moq. Finally, if the problem only surfaces with Azure DevOps, perhaps it would be better to ask in a place related to that?

**Comment by dariusz-wozniak** [comment] 2021-07-01 06:45
Sure thing, thank you for the info @stakx!

I will continue trying to resolve that.

**Comment by denjmpr** [comment] 2021-11-23 05:09
Hi,
This is also reproducible with TeamCity Enterprise 2021.1.1.
I also tried some different approaches found on the web - nothing helped me.
Thanks.

**Comment by Sl1ckR1ck** [comment] 2022-01-31 15:17
getting the same issue here. I understand that the issue may not be the fault of this library per say, but would be still good to document possible workaround here for other people who would naturally come here in search of  a solution.
