### ISSUE TITLE
CallBase is ignored when it's true and MockBehavior is Strict

### ISSUE THREAD

**Issue by ds1709** [devlooped/moq#1226] opened 2022-01-11 11:27 UTC
Moq version: 4.16.1
Platform: any

## Description
For virtual methods `CallBase` is ignored when it's `true` and `MockBehavior` set to `Strict`. `MockException` is thrown istead.

## Expected behaviour
Base metod implementation is called instead of MockException throwing.

### Tested class
```c#
public abstract class Foo
{
    public virtual void Bar()
    { 
    }
}
```

### Call
```c#
var fooMock = new Mock<Foo>(MockBehavior.Strict) { CallBase = true };
var foo = fooMock.Object;
foo.Bar(); // exception here
```

**Comment by stakx** [comment] 2022-01-23 12:44
`CallBase = true` (specified at the mock level) + `MockBehavior.Strict` is a combination that doesn't make much sense. One specifies that when a method call hasn't been set up, the base implementation  should be called; the other says to throw in the same case. Those are contradictory, and IMHO it is correct that `MockBehavior.Strict` takes preference.

Closing this as "by design" &ndash; even though the design obviously isn't optimal because it allows a contradictory mock setup. (But we can't do anything about that without a breaking change.)

**Closed as completed** 2022-01-23 12:44 UTC
Labels: wontfix, by design

**Comment by drewnoakes** [comment] 2023-05-10 07:58
(Came here via search engine.)

Is there a way to set up a given virtual member such that the default implementation executes, without any override? I don't want to specify different logic for the member in my test, but I do want it to be virtual for other classes to override.

---

**EDIT** Answering my own question. Yes, use `CallBase()`.

For example:

```c#
var fooMock = new Mock<Foo>(MockBehavior.Strict);
fooMock.Setup(o => o.Bar()).CallBase();
var foo = fooMock.Object;
foo.Bar(); // no exception
```
