### ISSUE TITLE
invalid path on linux

### ISSUE THREAD

**Issue by ivanjx** [devlooped/moq#1353] opened 2023-07-21 09:53 UTC
vscode wont show the correct error because moq uses the wrong path for the error message such as:
```
[xUnit.net 00:00:00.50]     server.Tests.Services.Registration.RegistrationServiceTest.SendOtpAsync_RateLimit [FAIL]
  Failed server.Tests.Services.Registration.RegistrationServiceTest.SendOtpAsync_RateLimit [39 ms]
  Error Message:
   Moq.MockException : ITimeService.Now invocation failed with mock behavior Strict.
All invocations on the mock must have a corresponding setup.
  Stack Trace:
     at Moq.FailForStrictMock.Handle(Invocation invocation, Mock mock) in C:\projects\moq4\src\Moq\Interception\InterceptionAspects.cs:line 182
   at Moq.Mock.Moq.IInterceptor.Intercept(Invocation invocation) in C:\projects\moq4\src\Moq\Interception\Mock.cs:line 27
   at Moq.CastleProxyFactory.Interceptor.Intercept(IInvocation underlying) in C:\projects\moq4\src\Moq\Interception\CastleProxyFactory.cs:line 107
   at Castle.DynamicProxy.AbstractInvocation.Proceed()
   at Castle.Proxies.ITimeServiceProxy.get_Now()
   at server.Services.Registration.RegistrationService.SendOtpAsync(String email, String username) in /home/user/Documents/projects/server/server/Services/Registration/RegistrationService.cs:line 136
   at server.Tests.Services.Registration.RegistrationServiceTest.SendOtpAsync_RateLimit() in /home/user/Documents/projects/server/server.Tests/Services/Registration/RegistrationServiceTest.cs:line 118
--- End of stack trace from previous location ---
```

related https://github.com/microsoft/vscode-dotnettools/issues/278

**Comment by stakx** [comment] 2023-07-21 21:09
Closing for several reasons:

* This issue is missing a minimally complete code example thst reproduces the issue.
* The issue isn't clearly stated. The error message does not contain any "path" at all. Also, what kind of path are you speaking of? File paths such as in the stack trace? Windows file paths despite you being on a Linux machine? If so, that's very likely beyond our control.

**Closed as completed by stakx** 2023-07-21 21:10 UTC
