### ISSUE TITLE
Mocking a method with "in" parameter of generic type

### ISSUE THREAD

**Issue by kaminova** [devlooped/moq#1136] opened 2021-01-28 17:15 UTC
Hello

I'm trying to mock a method with "in" parameter of generic type.
Repro:
```
    public readonly struct MyStruct
    {
        public int F1 { get; }
    }
    public interface ITester
    {
        void Method<T>(in T value) where T : struct;
    } 
	
    var mock = new Mock<ITester>();
    mock.Setup(m => m.Method(It.Ref<MyStruct>.IsAny));
	
    var t = new MyStruct();
    mock.Object.Method(in t);  //exception here
```

I got an exception: 

	`System.MissingMethodException : Method not found: 'Void Project1.Tests.ITester.Method(Project1.Tests.MyStruct ByRef)'.`

Am i missing something? (i use moq4.14.7)

**Comment by stakx** [comment] 2021-01-28 17:27
Duplicate of #1104 and #988. I'm going to leave this one open because it recently occurred to me in https://github.com/castleproject/Core/issues/430#issuecomment-756309040 that a partial workaround may be possible. If so, we need to wait for a fix in DynamicProxy & then update.

**Comment by stakx** [comment] 2021-03-07 15:33
Small update: It appears that updating to .NET 6 (once released) will take care of this problem. The issue described above is no longer reproducible on [.NET 6 Preview](https://dotnet.microsoft.com/download/dotnet/6.0).

**Comment by stakx** [comment] 2021-03-15 21:26
I am closing this issue as explained in #1148.

**Closed as completed by stakx** 2021-03-15 21:26 UTC
