### ISSUE TITLE
[FEATURE REQUEST] Implicit Type Casting from Mock to Object?

### ISSUE THREAD

**Issue by mathew-odwyer** [devlooped/moq#1105] opened 2020-11-19 04:45 UTC
I always find myself doing something like the following:

```csharp
var foo = new Mock<IFoo>();
var bar = new Bar(foo);
```

and then realizing I have to change `foo` to `foo.Object` in `Bar`'s constructor. Personally, I think it would be a great idea to allow implicit casting from `Mock<IFoo>` to `IFoo` 😸

**Comment by stakx** [comment] 2020-11-19 07:05
Duplicate of #1097. See there for an explanation why this won't work.

**Closed as completed by stakx** 2020-11-19 07:05 UTC
Labels: duplicate, wontfix, known limitation
