### ISSUE TITLE
Test method throwing exception with C# 9.0 init keyword

### ISSUE THREAD

**Issue by Fqadri** [devlooped/moq#1147] opened 2021-03-13 22:46 UTC
I have the following interface defined with C# 9.0

    public interface IState<TType>
    {
       string SomeId{ get; init; }
    }

When mocking in unit testing like `var state = new Mock<IState<string>>(MockBehavior.Strict);` it throws this exception

  Message: 
    Test method `MyAssembly.StateTest` threw exception: 
    `Castle.DynamicProxy.ProxyGenerationException`: There was an error in static constructor on type `Castle.Proxies.IState'1Proxy`. This is likely a bug in DynamicProxy. Please report it. ---> System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.TypeInitializationException: The type initializer for `'Castle.Proxies.IState'1Proxy'` threw an exception. ---> `System.MissingMethodException`: Method not found: `'void MyState.IState'1.set_SomeId(System.String)'`.

There is something breaking with Moq (4.13.0) and C# 9.0 `init` keyword ?

**Comment by stakx** [comment] 2021-03-13 23:11
Can you try running this on .NET 6 Preview and see whether that resolves this issue?

**Comment by Fqadri** [comment] 2021-03-14 00:39
@stakx, unfortunately we don't have plans yet to migrate from current `.NET 5.0` framework. I can create a separate project just to try this out on `.NET 6 preview` but a fix/workaround for `.NET 5.0` would be good.

**Comment by stakx** [comment] 2021-03-15 21:05
@Fqadri I ran a quick check. My suspicion turned out to be correct, this is yet another duplicate of #1136, #1104, and #988: [a .NET Reflection.Emit bug](https://github.com/dotnet/runtime/issues/25958) causes method signatures to be encoded incorrectly when the method signature contains modreqs (here: a [`modreq(System.Runtime.CompilerServices.IsExternalInit)` applied to the setter's return type](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/proposals/csharp-9.0/init#metadata-encoding)) and the method or its containing type is generic.

The only realistic course of action is for you to update to .NET 6 or later.

(I was recently [considering implementing a limited workaround in Castle DynamicProxy](https://github.com/castleproject/Core/issues/430#issuecomment-756309040), but even that turned out to be very difficult and costly, so it's probably not going to happen, esp. now with .NET 6 just around the corner.)

**Comment by stakx** [comment] 2021-03-15 21:25
I am closing this issue as explained in #1148.

**Closed as completed by stakx** 2021-03-15 21:25 UTC

**Comment by Fqadri** [comment] 2021-03-16 01:48
Ok thanks.
