### ISSUE TITLE
Setup with `in` parameter fails for generic methods

### ISSUE THREAD

**Issue by mteknight** [devlooped/moq#1104] opened 2020-11-18 13:08 UTC
I am trying to setup a method with **Moq 4.14.0** in a **.NET Core 3.1** solution. This method has a last `CancellationToken` parameter with the **in** modifier, as follows:

```
Task<BulkResponse> IndexMany<TDocument>(
            IEnumerable<TDocument> entities,
            IndexName indexName,
            in CancellationToken cancellationToken = default)
            where TDocument : class;
```

I have done some testing and it fails because it is generic. I have tried adding a similar non-generic method to the interface and then mocking works just as expected:

```
Task<BulkResponse> IndexMany(
            IEnumerable<string> entities,
            IndexName indexName,
            in CancellationToken cancellationToken = default);
```

Naturally, the exception I am getting is `MissingMethodException`.

**Comment by stakx** [comment] 2020-11-18 19:18
Duplicate of #988. That's due to a long-standing bug in the CLR. Not much we can do at this time. See the linked issue for further info. (It appears this will be fixed in .NET 6.)

**Closed as completed by stakx** 2020-11-18 19:18 UTC
Labels: duplicate, known limitation

**Comment by stakx** [comment] 2021-03-07 15:39
Small update: It appears that updating to .NET 6 (once released) will take care of this problem. The issue described above is no longer reproducible on [.NET 6 Preview](https://dotnet.microsoft.com/download/dotnet/6.0).

**Comment by stakx** [comment] 2021-03-15 21:26
If there's any further news on this, I'll post them in #1148.
